#!/usr/bin/env python3
"""cleanup_generated.py — sweep placeholder noise out of generated references.

Targets
-------
1.  references/components/<n>/api.md
    Drop `## X` sections whose body is just `_（无数据）_`, and rebuild the
    `## Contents` TOC to match. Empty sections are real signal: the upstream
    `tusen-ai/naive-ui` source genuinely has no events / slots / methods /
    sub-components for many components.

2.  references/components/<n>/patterns.md
    Collapse `- - X` (double-bullet artefact from the template) into `- X`.
    This is caused by `antipatterns()` returning a list of "- foo" lines and
    the template wrapping each in an extra `- `.

The script is **idempotent**: re-running it on already-clean files is a no-op.
Use `--dry-run` to preview the diff before writing.

Scope
-----
Only files under `<skill>/references/components/<n>/{api,patterns}.md` are
touched. The default `--skill` is `naive-ui` (relative to this script's
parent directory), which matches the `naive-ui-skill/` repo layout:

    naive-ui-skill/
    ├── scripts/cleanup_generated.py    ← this file
    └── naive-ui/                       ← default --skill target
        └── references/components/…

A file is recognised as generated by either:
  - the `<!-- generated -->` HTML marker in the frontmatter prose, or
  - the frontmatter key `metadata.generatedBy` (any value).

Safety
------
-  `## Props` is **never** dropped. If the body is empty, the script aborts
   with a non-zero exit so the operator can investigate the extractor.
-  The frontmatter (between the leading `---` markers) is preserved verbatim.
-  File encoding stays UTF-8; line endings are normalised to LF on write.

Usage
-----
    python scripts/cleanup_generated.py                # rewrite in place
    python scripts/cleanup_generated.py --dry-run      # show summary, no writes
    python scripts/cleanup_generated.py --scope api    # only api.md
    python scripts/cleanup_generated.py --scope patterns
    python scripts/cleanup_generated.py --skill ../naive-ui
"""
from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path

# Project root is the directory that contains both `scripts/` and `naive-ui/`.
PROJECT_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_SKILL = PROJECT_ROOT / "naive-ui"

# Section headings that may be dropped if empty.  Anything not in this allow-list
# is considered load-bearing and is never removed.
DROPPABLE_SECTIONS = {
    "Events",
    "Slots",
    "Methods / Exposes",
    "Sub Components",
}

# Placeholder text emitted by rows_to_table([]) in generate_references.py.
PLACEHOLDER_RE = re.compile(r"^_（无数据）_\s*$", re.M)
# Compiled for performance once
EMPTY_LINE_RE = re.compile(r"^\s*$", re.M)
DOUBLE_BULLET_RE = re.compile(r"^- - ", re.M)
HEADING_RE = re.compile(r"^(##\s+.+?)\s*$", re.M)


@dataclass
class ChangeReport:
    path: Path
    before: str
    after: str

    @property
    def changed(self) -> bool:
        return self.before != self.after

    def summary(self, root: Path | None = None) -> str:
        b = self.before.splitlines()
        a = self.after.splitlines()
        rel = self.path.relative_to(root) if root else self.path
        return f"  {rel}: {len(b)} -> {len(a)} lines"


def split_frontmatter(text: str) -> tuple[str, str]:
    """Return (frontmatter_block_with_newlines, body)."""
    if not text.startswith("---"):
        return "", text
    end = text.find("\n---", 3)
    if end < 0:
        return "", text
    return text[: end + 4], text[end + 4 :]


def is_empty_section_body(body: str) -> bool:
    """True if the section body has no real content. Two cases qualify:

    1.  Body is just `_（无数据）_` (legacy generator placeholder) — kept for
        backwards-compat with files generated before the empty-body change.
    2.  Body is whitespace-only after stripping blockquote lines — the new
        `section_block()` helper returns an empty string when both rows and
        notes are absent, so the template leaves a heading followed by
        nothing but blanks.
    """
    stripped = re.sub(r"^>\s.*$", "", body, flags=re.M)
    cleaned = stripped.strip()
    return cleaned == "" or cleaned == "_（无数据）_"


def clean_api_md(text: str) -> tuple[str, list[str]]:
    """Return (new_text, list_of_dropped_section_names)."""
    dropped: list[str] = []
    fm, body = split_frontmatter(text)

    # Iterate sections in order, drop empty ones
    parts = re.split(r"(^## .+$)", body, flags=re.M)
    # parts = [pre, heading, body, heading, body, ...]
    new_parts: list[str] = [parts[0]]  # prologue (after frontmatter, before first ##)
    i = 1
    while i < len(parts):
        heading_line = parts[i]
        section_body = parts[i + 1] if i + 1 < len(parts) else ""
        title = heading_line.lstrip("## ").strip()
        if title in DROPPABLE_SECTIONS and is_empty_section_body(section_body):
            dropped.append(title)
            i += 2
            continue
        new_parts.append(heading_line)
        new_parts.append(section_body)
        i += 2

    new_body = "".join(new_parts)

    # Rebuild the `## Contents` TOC if one exists, listing only sections
    # that survived the drop. Match the entire bullet block (heading +
    # blank line + every `- [...]` line) and replace it in one shot.
    new_body = re.sub(
        r"##\s+Contents\s*\n+(?:- \[.+?\]\(#.+?\)\n)+",
        lambda _m: "## Contents\n\n" + build_contents(new_body),
        new_body,
        count=1,
    )

    return fm + new_body, dropped


def build_contents(body: str) -> str:
    """Return the bullet list that goes under `## Contents`, derived from the
    headings present in `body`."""
    headings = HEADING_RE.findall(body)
    # Drop the Contents heading itself from the TOC; the dispatcher reads
    # the H1 + Contents as a single self-link.
    lines: list[str] = []
    for h in headings:
        title = h.lstrip("## ").strip()
        if title == "Contents":
            continue
        anchor = re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-")
        lines.append(f"- [{title}](#{anchor})")
    if not lines:
        return ""
    return "\n".join(lines) + "\n"


def clean_patterns_md(text: str) -> str:
    """Collapse `- - X` (double-bullet) into `- X`."""
    return DOUBLE_BULLET_RE.sub("- ", text)


def is_generated(path: Path, skill_root: Path) -> bool:
    """All files under `<skill>/references/components/<n>/{api,patterns}.md` are
    generated by `scripts/generate_references.py`; trust the path."""
    rel = path.relative_to(skill_root)
    parts = rel.parts
    return (
        len(parts) == 4
        and parts[0] == "references"
        and parts[1] == "components"
        and parts[3] in ("api.md", "patterns.md")
    )


def main() -> int:
    ap = argparse.ArgumentParser(description="Clean up generated references.")
    ap.add_argument(
        "--skill",
        default=str(DEFAULT_SKILL),
        help="Skill directory containing references/components/ (default: %(default)s).",
    )
    ap.add_argument("--scope", choices=("api", "patterns", "all"), default="all")
    ap.add_argument(
        "--dry-run",
        action="store_true",
        help="Report what would change without writing any files.",
    )
    args = ap.parse_args()
    skill_root = Path(args.skill).resolve()

    reports: list[ChangeReport] = []
    for sub in ("api.md", "patterns.md"):
        if args.scope == "api" and sub != "api.md":
            continue
        if args.scope == "patterns" and sub != "patterns.md":
            continue
        for path in sorted((skill_root / "references" / "components").glob(f"*/{sub}")):
            if not is_generated(path, skill_root):
                # generated files all carry the marker; skip anything that doesn't
                continue
            original = path.read_text(encoding="utf-8")
            if sub == "api.md":
                cleaned, _dropped = clean_api_md(original)
            else:
                cleaned = clean_patterns_md(original)
            reports.append(ChangeReport(path=path, before=original, after=cleaned))

    changed = [r for r in reports if r.changed]
    print(f"Scanned {len(reports)} files; {len(changed)} would change.")
    if changed:
        print("Changes:")
        for r in changed:
            print(r.summary(skill_root))
        # Safety check: count Props drops
        api_reports = [r for r in changed if r.path.name == "api.md"]
        if api_reports:
            for r in api_reports:
                _, dropped = clean_api_md(r.before)
                if "Props" in dropped:
                    print(f"  REFUSE: {r.path} would drop ## Props — aborting.", file=sys.stderr)
                    return 2
        if args.dry_run:
            print("\n--dry-run: no files written. Re-run without --dry-run to apply.")
            return 0
        for r in changed:
            r.path.write_text(r.after, encoding="utf-8")
        print(f"Wrote {len(changed)} files.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
